name: tests-check
on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run make Install
        run: make install

      - name: Run make Lint
        run: make lint

      - name: Run make test & code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.9c862f3d0f7715ac200e6df20ccd4a33353e13edbd6a38a51899a4495f8e112c }}
        with:
          coverageCommand: make test-coverage
          debug: true
